# Test your FastAPI endpoints

PATCH http://127.0.0.1:8000/bi/update_data/cars
Accept: application/json

###

GET http://127.0.0.1:8000/bi/get/cars
Accept: application/json

###

GET http://127.0.0.1:8000/bi/get_condition/invoices?day=2024-01-30
Accept: application/json

###

GET http://127.0.0.1:8000/bi/get/react_drivers
Accept: application/json

###